### ISSUE TITLE
Integrate vue.js instead of JQuery

### ISSUE THREAD

**Issue by astroanu** [codebreez/collejo#1]
Most of the UI currently uses a Jquery based framework for displaying content. We need to remove this and replace that with vue.js.

**Comment by logaretm** [comment]
I would be happy if I can help with this one, any guidelines on how I can start?

**Comment by astroanu** [comment]
The idea is to remove jquery code one module at a time. You can start with the simplest module such as `Auth`. 

[https://github.com/CodeBreez/collejo-app/tree/master/src/modules/Auth/resources/views](https://github.com/CodeBreez/collejo-app/tree/master/src/modules/Auth/resources/views)

I haven't made a documentation for developers (yet). I want to do it soon so others can collaborate.

I still have no idea on how to migrate to vuejs entirely. But doing so will save a lot of unnecessary code form being added to the codebase. 

I'm thinking using vue components to do this would make easier. But then we need to think of a way for the gulp scripts to pick these files and compile. 

But let's not make things really complicated. We can start by making a single vue app for each main template file. So the [ login blade](https://github.com/CodeBreez/collejo-app/blob/master/src/modules/Auth/resources/views/login.blade.php) will have a vue component that handles only login, and so on for other modules/pages.

I think this is the easiest way to start ? :)

**Comment by logaretm** [comment]
Sure, I can start with custom webpack setup for now, having multiple entries for each module, can be later integrated into gulp I think.

I will familiarize myself with the project and start working on it.

**Comment by logaretm** [comment]
I've setup both `collejo` repo and the `collejo-app` repositories and tied them using composer, but I can't figure how to test my changes to the login page, as all routes redirect to `auth/login` which doesn't exist resulting in 404s.

When I list the available routes using `php artisan route:list` only the `/` and `/dash` routes are showing. am I missing something in the installation process?

**Comment by astroanu** [comment]
You will need to run `php artisan install` to install, this should run the migrations and should also create an admmin user for you. 

What does running `php artisan module:list` show ?

I use this repo [https://github.com/astroanu/collejo-workbench](https://github.com/astroanu/collejo-workbench) as a development workbench, so my source code is not inside the vendor folder.

**Comment by logaretm** [comment]
Doesn't list any of the modules, so here what I have done so far:

- Cloned `collejo-app` repository, and installed its dependencies (composer, npm).
- Cloned `collejo` repository, and pointed the `collejo-app` in `composer.json` to use the local one I cloned.
- Run `php artisan install` in `collejo` repo and setup my admin account, no issues there.
- Run `php artisan serve` and I always get 404, no routes are being picked up, no modules either.

 I will try the workbench.

**Comment by astroanu** [comment]
Yea, try the workbench. It should be easier for you to develop there. I even updated the readme.md for setting it up for you.
