### ISSUE TITLE
How to create test users

### ISSUE THREAD

**Issue by anarayn** [codebreez/collejo#11]
I tried this app and found it interesting. I am able to install and run this in my local but I am not able to log in, how can I create test users?

**Comment by astroanu** [comment]
You should be able to create an admin user from the cli. 

`php artisan admin:create`

After that login using that account to add other users.

**Comment by anarayn** [comment]
Thanks a lot! 
It worked and I am able to log in now but still, I don't see any menu option. will I have to do some changes to display menus?
