### ISSUE TITLE
Can not run database migrations to create tables

### ISSUE THREAD

**Issue by sirBobz** [codebreez/collejo#4]
I installed the project via composer as composer create-project codebreez/collejo

Following your installation guide, I set up my database credentials.

Then I tried to create the database migrations using the `migrate:copy` artisan command but threw a 

`[2018-02-03 02:54:32] local.ERROR: ErrorException: copy(/var/www/html/collejo/database/migrations/0_0_0_000090_create_user_role_table.php): failed to open stream: No such file or directory in /var/www/html/collejo/vendor/codebreez/collejo-app/src/Console/Commands/MigrateCopy.php:41`

On checking, clearly the files do not exist on `database/migrations` directory.

Kindly advice

**Comment by astroanu** [comment]
Hi, were you able to get through ?

It is a known bug. just create a new directory in the `database` folder by the name `migrations`

`<project_path\database\migrations`

then re-run `migration:copy` artisan command
